.TH BOOT_MACOS 1 "1970-1-1" "v1.0" "Custom Scripts Manual"
.SH NAME
boot_macos \- Sets the next boot only to boot into macos using asahi-bless
.SH SYNOPSIS
.B boot_macos
.SH DESCRIPTION
.B boot_macos
A simple script which sets only the next boot to macos. Needs sudo permissions to use asahi-bless
.SH SEE ALSO
.MR sudo 1
