.TH BRIGHTNESS 1 "1970-1-1" "v1.0" "Custom Scripts Manual"
.SH NAME
brightness \- adjust display backlight brightness using brightnessctl
.SH SYNOPSIS
.B brightness
[\fIOPTION\fR] [\fIAMOUNT\fR]
.SH DESCRIPTION
.B brightness
is a simple wrapper script that provides a standardized interface to the
.MR brightnessctl 1
utility. It allows users to query or modify the display brightness level. If no options is provided,
it displays the current brightness level. Most modifications allow a second arg as a num between 0-100 for brightness. The default is 5.
.SH OPTIONS
.TP
.B \-\-get
Retrieve the current brightness level as a percentage (0-100).
.TP
.B \-\-inc \fR[\fIAMOUNT\fR]
Increase brightness by \fIAMOUNT\fR. If \fIAMOUNT\fR is omitted, it defaults to 5.
.TP
.B \-\-dec \fR[\fIAMOUNT\fR]
Decrease brightness by \fIAMOUNT\fR. If \fIAMOUNT\fR is omitted, it defaults to 5.
.TP
.B \-\-set \fIAMOUNT\fR
Set the brightness to exactly \fIAMOUNT\fR. This option requires an argument.
.TP
.B \-h, \-\-help
Display the help menu and exit.
.SH EXAMPLES
.TP
.B brightness \-\-inc
Increase the display brightness by 5%.
.TP
.B brightness \-\-get
Output the current brightness percentage to standard output.
.TP
.B brightness \-\-inc 10
Increase the display brightness by 10%.
.TP
.B brightness \-\-set 50
Set the display brightness to exactly 50%.
.SH ENVIRONMENT
The script relies on the presence of the
.MR brightnessctl 1
command in the system's PATH.
.SH BUGS
Arguments for \fIAMOUNT\fR must be integers between 0 and 100.
.SH SEE ALSO
.MR brightnessctl 1 ,
.MR cut 1 ,
.MR tr 1
