.TH LOCK 1 "1970-1-1" "v1.0" "Custom Scripts Manual"
.SH NAME
lock \- Generates hyprlock panels and locks the screen
.SH SYNOPSIS
.B lock
.SH DESCRIPTION
.B lock
is a utility that generates panels using
.B $NIX_CFG_DIR/config/hypr/hyprscripts/hyprlock-run/panels
and runs hyprlock with -q
.SH FILES
.B The panels script
.I $NIX_CFG_DIR/config/hypr/hyprscripts/hyprlock-run/panels
.SH SEE ALSO
.MR magick 1
