.TH VOLUME 1 "1970-1-1" "v1.0" "Custom Scripts Manuals"
.SH NAME
volume \- a wrapper for pamixer to manage speaker and microphone audio
.SH SYNOPSIS
.B volume
[\fIOPTION\fR]
.SH DESCRIPTION
.B volume
is a command-line utility that simplifies audio management using
.MR pamixer 1 .
It provides easy-to-use flags for increasing, decreasing, or toggling mute 
for both default sinks (speakers) and sources (microphones).
.PP
If the device is muted when an increase or decrease command is issued, 
the script will automatically unmute the device before adjusting the level.
.SH OPTIONS
.TP
.B \-\-get
Retrieve the current speaker volume percentage.
.TP
.B \-\-inc [VALUE]
Increase the speaker volume by \fIVALUE\fR% (default 5). 
Allows boosting up to 150%.
.TP
.B \-\-dec [VALUE]
Decrease the speaker volume by \fIVALUE\fR% (default 5).
.TP
.B \-\-set [VALUE]
Set the speaker volume to \fIVALUE\fR%. Errors on \fIVALUE\fR% not being a number.
.TP
.B \-\-mute
Toggle the mute status of the default speaker.
.TP
.B \-\-get\-mic
Retrieve the current microphone volume percentage.
.TP
.B \-\-inc\-mic [VALUE]
Increase the microphone volume by \fIVALUE\fR% (default 5).
.TP
.B \-\-dec\-mic [VALUE]
Decrease the microphone volume by \fIVALUE\fR% (default 5).
.TP
.B \-h, \-\-help
Display the help menu and exit.
.SH EXAMPLES
.TP
.B volume \-\-inc
Unmutes the speakers (if necessary) and increases volume by 5%.
.TP
.B volume \-\-get\-mic
Returns the current recording level of the default microphone.
.TP
.B volume \-\-inc
Increases volume by the default 5%.
.TP
.B volume \-\-inc 20
Increases volume by 20%.
.TP
.B volume \-\-set 20
Sets the volume to 20% on the speakers.
.SH NOTES
The speaker volume increase is limited to 150% to prevent hardware damage 
while allowing levels above the standard 100% threshold.
.SH SEE ALSO
.MR pamixer 1 ,
.MR pactl 1
