music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
pid_file           "~/.config/mpd/pid"
log_file					 "/dev/null"
state_file         "~/.config/mpd/state"

bind_to_address    "~/.config/mpd/socket"

audio_output {
    type           "pipewire"
    name           "PipeWire Output"
}
