general {
    disable_loading_bar = true
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
    ignore_empty_input = true
    ttl = 0
}

background {
    monitor =
    path = ~/nixos-cfg/wallpapers/blockwavemoon.png
    color = $base
    blur_passes = 2
    blur_size = 4
    noise = 0.01
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = $muted
    inner_color = $surface
    font_color = $text
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

# Current time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $text
    font_size = 64
    font_family = JetBrains Mono Nerd Font
    position = 0, -300
    halign = center
    valign = center
}

# Current date
label {
    monitor =
    text = cmd[update:10000] echo "$(date +"%A, %B %d")"
    color = $subtle
    font_size = 20
    font_family = JetBrains Mono Nerd Font
    position = 0, -220
    halign = center
    valign = center
}

# User label
label {
    monitor =
    text = Hey <span foreground="$rose">$USER</span>!
    color = $text
    font_size = 18
    font_family = JetBrains Mono Nerd Font
    position = 0, -160
    halign = center
    valign = center
}

# Caps lock indicator
label {
    monitor =
    text =  <span foreground="$gold">Caps Lock</span>
    color = $muted
    font_size = 16
    font_family = JetBrains Mono Nerd Font
    position = 0, -380
    halign = center
    valign = center
    inherit = input-field
}

# Weather
 label {
     monitor =
     text = cmd[update:1800000] curl -s "wttr.in/?format=3"
     color = $foam
     font_size = 14
     font_family = JetBrains Mono Nerd Font
     position = 20, 20
     halign = left
     valign = bottom
 }

# System stats
 label {
     monitor =
     text =  <span foreground="$iris">$((100-$(vmstat 1 2 | tail -1 | awk '{print $15}')))%</span>   <span foreground="$pine">$(free -h | awk '/^Mem/ {print $3}')</span>
     color = $muted
     font_size = 14
     font_family = JetBrains Mono Nerd Font
     position = 20, 50
     halign = left
     valign = bottom
 }
