#!/usr/bin/env bash

step=5

print_help() {
  echo "Usage: brightness [OPTION]"
  echo "Args:"
  echo "--get	   Get the brightness"
  echo "--inc 	   Increase the brightness by 5"
  echo "--dec 	   Decrease the brightness by 5"
  echo "-h, --help Show this menu"
}

get_brightness() {
  brightnessctl -m | cut -d, -f4 | tr -d '%'
}

change_brightness() {
  local p=$1
  local cur new

  cur=$(get_brightness)
  new=$((cur + p))

  ((new < 5)) && new=5
  ((new > 100)) && new=100

  brightnessctl set "${new}%"
}

case $1 in
  "--get")
    get_brightness
    ;;
  "--inc")
    change_brightness "$step"
    ;;
  "--dec")
    change_brightness "-$step"
    ;;
  "-h" | "--help")
    print_help
    ;;
  *)
    print_help
    echo -e "\n\nCurrent brightness: $(get_brightness)"
    ;;
esac
