#!/usr/bin/env bash

read -d '' -r USAGE <<- EOF
Usage: screenshot [flags]

Screenshots the screen

Options
  -h Prints this help message
  -c Writes to clipboard with wl-copy
  -s Screenshots all outputs (default behavior of grim)
  -n Notify the user (requires notify-send)
  -d Writes to either a specified directory or to ~/Screenshots and does not write to clipboard

If neither -c or -d are specified then the screenshot will not be saved
EOF

clip=false
full=false
noti=false
fs=false
od="$HOME/Screenshots"

parse_opts() {
  test -eq $# 0 && echo "$USAGE" && exit 0
  local OPTIND OPTARG opt
  while getopts 'hcsd' opt; do
    case "$opt" in
      c)
	clip=true
	;;
      s)
	full=true
	;;
      n)
	noti=true
	;;
      d)
	fs=true
	eval nxtopt=\${$OPTIND}
	if [[ -n $nxtopt && $nxtopt != -* ]]; then
	  ((OPTIND++))
	  od=$nxtopt
	fi
	;;
      h|*)
	echo "$USAGE"
	exit 0
	;;
    esac
  done
  ($fs) && mkdir -p "$od"
}

notify_usr() {
  local status=$1
  local title="Screenshot taken"
  local icon="camera-photo"
  local body="Screenshot of"

  !(test -eq $status 0) && title="Failed to screenshot" icon="dialog-error" body="Failed to take a screenshot of"
  ($full) && body="${body} all wayland outputs"
  !($full) && body="${body} the selected area"
  !(test -eq $status 0) && body="${body} and have it"
  (($clip) && ($fs)) && body="${body} saved to clipboard and $od"
  ($clip) && body="${body} saved to clipboard"
  ($fs) && body="${body} saved to $od"

  notify-send -i="$icon" "$title" "$body"
}

take_scr() {
  CMD="grim"
  !($full) && CMD="${CMD} -g \"\$(slurp)\""
  ($fs) && CMD="${CMD} \"$od/$(date +"%Y-%m-%d_%H-%M-%S").png\""
  ($clip) && CMD="${CMD} -t png - | wl-copy -t image/png"
  (!($fs) && !($clip)) && CMD="" # grim will take a screenshot by default if I don't use this
  $CMD
  STS=$?
  ($noti) && notify_usr $STS
}

parse_opts "$@"
take_scr
