#!/usr/bin/env bash

read -d '' -r USAGE <<- EOF
Usage: screenshot [flags]

Screenshots the screen

Options
  -h Prints this help message
  -c Writes to clipboard with wl-copy
  -s Screenshots all outputs (default behavior of grim)
  -n Notify the user (requires notify-send)
  -d Writes to either a specified directory or to ~/Screenshots and does not write to clipboard

If neither -c or -d are specified then the program will exit with error
EOF

clip=false
full=false
noti=false
fs=false
od="$HOME/Screenshots"

parse_opts() {
  test "$#" -eq 0 && echo "$USAGE" && exit 0
  local OPTIND OPTARG opt
  while getopts 'hcsnd' opt; do
    case "$opt" in
      c)
	clip=true
	;;
      s)
	full=true
	;;
      n)
	noti=true
	;;
      d)
	fs=true
	eval nxtopt=\${$OPTIND}
	if [[ -n $nxtopt && $nxtopt != -* ]]; then
	  ((OPTIND++))
	  od=$nxtopt
	fi
	;;
      h|*)
	echo "$USAGE"
	exit 0
	;;
    esac
  done
  ($fs) && mkdir -p "$od"
}

notify_usr() {
  local status=$1
  local title="Screenshot taken"
  local body="Screenshot of"

  !(test $status -eq 0) && title="Failed to screenshot" && body="Failed to take a screenshot of"
  ($full) && body="${body} all wayland outputs"
  !($full) && body="${body} the selected area"
  !(test $status -eq 0) && body="${body} and have it"
  (($clip) && ($fs)) && body="${body} saved to clipboard and $od"
  ($clip) && !($fs) && body="${body} saved to clipboard"
  ($fs) && !($clip) && body="${body} saved to $od"

  notify-send "$title" "$body"
}

take_scr() {
  local cmd="grim"
  local sts=0

  (!($clip) && !($fs)) && echo "No output specified (use -c for clipboard or -d for file)" && exit 1
  !($full) && cmd="${cmd} -g \"\$(slurp)\""
  (($fs) && ($clip)) && cmd="${cmd} - | tee \"$od/$(date +"%y-%m-%d_%H-%M-%S").png\" | wl-copy -t image/png"
  (($fs) && !($clip)) && cmd="${cmd} \"$od/Screenshot-$(date +"%y-%m-%d_%H-%M-%S").png\""
  (($clip) && !($fs)) && cmd="${cmd} - | wl-copy -t image/png"
  
  eval $cmd
  sts=$?
  ($noti) && notify_usr $sts
}

parse_opts "$@"
take_scr
