#!/usr/bin/env bash

print_help() {
  echo "Usage: volume [OPTIONS]"
  echo "Args:"
  echo "--get	   Get the current volume"
  echo "--inc 	   Increase the volume"
  echo "--dec 	   Decrease the volume"
  echo "--get-mic  Get the microphone volume"
  echo "--inc-mic  Increase the microphone volume"
  echo "--dec-mic  Decrease the microphone volume"
  echo "-h, --help Show this help menu"
}

get_vol() {
  vol=$(pamixer --get-volume)
  echo "$vol"
}

inc_vol() {
  if [ "$(pamixer --get-mute)" == "true" ]; then
    toggle_mute
  else 
    pamixer -i 5 --allow-boost --set-limit 150
  fi
}

dec_vol() {
  if [ "$(pamixer --get-mute)" == "true" ]; then
    toggle_mute
  else
    pamixer -d 5
  fi
}

toggle_mute() {
  if [ "$(pamixer --get-mute)" == "false" ]; then
    pamixer -m
  elif [ "$(pamixer --get-mute)" == "true" ]; then
    pamixer -u
  fi
}

toggle_mic() {
  if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
    pamixer --default-source -m
  elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
    pamixer -u --default-source
  fi
}

get_mic_vol() {
  vol=$(pamixer --default-source --get-volume)
  echo "$vol"
}

inc_mic_vol() {
  if [ "$(pamixer --default-source --get-mute)" == "true" ]; then
    toggle_mic
  else
    pamixer --default-source -i 5
  fi
}

dec_mic_vol() {
  if [ "$(pamixer --default-source --get-mute)" == "true" ]; then
    toggle_mic
  else
    pamixer --default-source -d d
  fi
}

case $1 in
  "--get")
    get_vol
    ;;
  "--inc")
    inc_vol
    ;;
  "--dec")
    dec_vol
    ;;
  "--get-mic")
    get_mic_vol
    ;;
  "--inc-mic")
    inc_mic_vol
    ;;
  "--dec-mic")
    dec_mic_vol
    ;;
  "-h" | "--help")
    print_help
    ;;
  *)
    print_help
    echo -e "\n\nCurrent volume: $(get_vol)"
    ;;
esac
